services:
  - type: web
    name: chen-abot
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false